### ISSUE TITLE
Navbar component

### ISSUE THREAD

**Issue by khaoulasara** [khaoulasara/portfolio#1]
**_Issue Description_**
**Task Title:**
Design and Implement Navbar Component

**Task Description:**
Create a responsive Navbar for the personal portfolio website with the following elements:

- Home, About Me, Projects, and Contact buttons
- Responsive Hamburger menu for mobile devices
- Optional social media icons (LinkedIn, GitHub, Twitter)

**Subtasks:**

- [ ] Design Navbar UI

- [ ] Implement Navbar Structure #XX:

- [ ] Add mobile-friendly functionality.

- [ ] Add Social Media Icons

- [ ] Test across devices and browsers.
